### ISSUE TITLE
evaluation algorithm and mate

### ISSUE THREAD

**Issue by tissatussa** [bagaturchess/Bagatur#11] opened 2021-11-17 15:08 UTC
hi, i just stumbled upon this position and i did some tests with several engines, including Bagatur :

![bagatur_mate5_diagram](https://user-images.githubusercontent.com/1109281/142226231-8830fd20-e6c0-4752-81a0-fd936c059344.png)

8/5q2/1p1K3p/7P/2k3P1/8/8/8 b - - 0 48

Black to move : Qf6+ is mate in 5.  Many engines find this very fast, even some simple engines, often within ten seconds -SF 14 finds mate-in-5 within one second- but Bagatur seems struggling to find best move (i used MPV 7 and 1 in SCID) :

![bagatur_mate_eval](https://user-images.githubusercontent.com/1109281/142226270-2bb01c63-5493-428d-85a3-554dfa3e77ec.png)

![bagatur_mate5_eval](https://user-images.githubusercontent.com/1109281/142226604-6b4d1344-01c1-4a59-b5b7-5e46b7037404.png)

**Comment by bagaturchess** [comment] 2021-12-07 17:22
This is again interesting finding - thanks a lot!

I tested this position with many runs and it is reproducible on Dev version as well.
In very rare cases Bagatur finds the mate in less than 10 seconds.
In most cases it takes a long time - there was one run, where 700 seconds were necessary.

I found the main reason - the Late Move Reduction (LMR).
It is quite "aggressive" in Bagatur.
The formula gives 1 or even 2 moves reduction more than what I have seen in articles and other engines.

Such positions are very nice, because they are boundary positions, which well show if there is an heuristic in the engine, which is not adjusted well.

I could reduce the LMR reduction to find this mate in 5 moves but also fit in 10 seconds.

Is this ok from your perspective?

Best regards,
Krasimir

**Comment by tissatussa** [comment] 2021-12-07 17:39
In texts of chess engines i often read the term "LMR" .. i have only a vague understanding what this means, but i can imagine .. 

What can be a good solution for Bagatur to solve this mate-in-# problem and other "boundary positions" ?
I don't know, i'm not into engine programming .. if adjusting the LMR helps, it's OK with me .. but such change should not influence other functionality too much, i think.  I leave it up to you.  I can test the resulting new Bagatur version, and i can post other "irregular" position when i find them.

**Comment by bagaturchess** [comment] 2021-12-07 17:54
Ok, thanks, I will decrease the LMR it in order to find this mate in up to 10 seconds each time.

The background: I find the reason relatively fast, because in the past I also found similar issues with LMR formula.
I just prefer to see Bagatur going in bigger depths without decreasing its ELO rating and this is set to the possible maximum.
My own explanation is that it perform bad in given positions but better in other and all these balances in regards to ELO.

But with this position and your tests it looks like only Bagatur cannot find the mate in up to 10 seconds - this has to be fixed.

P.S. This is a description of LMR, which looks short and well explained https://www.chessprogramming.org/Late_Move_Reductions

**Comment by bagaturchess** [comment] 2021-12-09 15:50
I have just push my final changes for LMR.
Everything looks fine from the last tournament with these changes:

![image](https://user-images.githubusercontent.com/17782785/145429243-fa8cfa4a-64d7-4599-b98d-c25245b0e5af.png)

**Comment by tissatussa** [comment] 2021-12-09 15:55
honestly, i understand only 50% of these stats : is -7 the max ELO loss ?  Not much then.

**Comment by bagaturchess** [comment] 2021-12-09 15:59
Yes, we can fully ignore it, as it is below the standard error out of 95 games.

**Comment by bagaturchess** [comment] 2021-12-09 16:25
I forgot to mention how this looks like from depth perspective: now Bagatur goes 5 moves shallower. I have to live with this :-)

**Comment by bagaturchess** [comment] 2021-12-11 20:02
Hi, this needs more small adjustments and tests, because with more games the strength difference becomes -21 ELO.
I have decrease it too much and now gave to shift it back a little bit. :-)

**Comment by bagaturchess** [comment] 2021-12-13 14:25
This looks better, now it is only 1-2-3 moves shallower, doesn't have ELO decrease and solves the +5 mate postion:
![image](https://user-images.githubusercontent.com/17782785/145829806-2d2ff86c-b794-4930-b514-93bf2fafae16.png)

**Comment by bagaturchess** [comment] 2022-01-01 14:33
Happy New Year 2022! I wish good health and good mood!
P.S. the version 3.0 is released and your feedback is welcome! ;-) I will close this issue.

**Closed** 2022-01-01 14:33 UTC
Labels: enhancement
